# Generated by Django 2.0.5 on 2018-05-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180511_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='id',
        ),
        migrations.AddField(
            model_name='film',
            name='movie_id',
            field=models.CharField(default='', max_length=8, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
